In [ ]:
import tensorflow as tf
import open3d as o3d
import numpy as np
from models.pcn import *
from models.pccn import *
import os
import open3d_util

print(tf.__version__)
print(o3d.__version__)

## Dataloader Development

In [ ]:
from datagenerator import DataGenerator

def get_file_paths(complete_dir, training=True):
    mid_pt = int(len(os.listdir(complete_dir))*7/9)
    start = 0 if training else mid_pt
    end = mid_pt if training else None
    return sorted(os.listdir(complete_dir))[start:end]

complete_dir = "data/complete/"
ds_train = DataGenerator(get_file_paths(complete_dir), complete_dir)
print((ds_train[2][0].shape))

In [ ]:
from dataloader_2 import Dataloader
complete_dir = "data/complete/"
ds_valid = Dataloader(complete_dir, is_training=False, batch_size=8)
print(ds_valid.counter)
ds_iter = iter(ds_valid)
# batch = next(ds_iter)
# print(batch[0].shape,batch[1],batch[2].shape)
# print(sum(batch[1]))

In [ ]:
print(len(ds_valid.list_pcd_path)//8)
c = 0
for id, data in enumerate(ds_valid):
    assert sum(data[1]) == data[0].shape[1]
    c+=1
    if c % 10: print("-",end=" ")
    # print(data[0].shape, end=" | ")
print(c, ds_iter.counter)

In [ ]:
class Geek:
    def __call__(self):
        print('Hello GeeksforGeeks')

geek = Geek()
geek()

In [1]:
import tensorflow as tf
from dataloader import Dataloader
ds_train = Dataloader(complete_dir="data/complete/", is_training=True, batch_size=1)
ds_train = tf.data.Dataset.from_generator(ds_train, output_types=(tf.float32, tf.int32, tf.float32), output_shapes=((), (), ()))

2022-07-25 21:51:15.866133: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
2022-07-25 21:51:15.866168: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


2022-07-25 21:51:18.390522: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
2022-07-25 21:51:18.390646: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
2022-07-25 21:51:18.390747: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/cuda/extras/CUPTI/lib64
2022-07-25 21:51:18.390848: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: li

In [2]:
for (a,b,c) in ds_train.repeat().batch(8).take(10):
    print(a.shape)

2022-07-25 21:51:20.976028: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2022-07-25 21:51:21.065970: W tensorflow/core/framework/op_kernel.cc:1680] Invalid argument: TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was (tf.float32, tf.int32, tf.float32), but the yielded element was tf.Tensor(
[[[ 1.0383280e-03 -1.5828928e-03  3.7101896e-03]
  [ 6.1125058e-05 -7.3752232e-04  2.3326376e-03]
  [ 9.6225485e-05 -5.3882645e-04  1.2442997e-03]
  ...
  [-9.0772845e-02  5.4567087e-02  4.6876539e-02]
  [-9.0408914e-02  5.4436173e-02  4.6672925e-02]
  [-8.8086993e-02  5.4665931e-02  4.6051532e-02]]], shape=(1, 1420, 3), dtype=float32).
Traceback (most recent call last):

  File "/home/wrs/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 898, in generator_py_func
    flattened_values = nest.flatten_up_to(output_types, value

InvalidArgumentError: TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was (tf.float32, tf.int32, tf.float32), but the yielded element was tf.Tensor(
[[[ 1.0383280e-03 -1.5828928e-03  3.7101896e-03]
  [ 6.1125058e-05 -7.3752232e-04  2.3326376e-03]
  [ 9.6225485e-05 -5.3882645e-04  1.2442997e-03]
  ...
  [-9.0772845e-02  5.4567087e-02  4.6876539e-02]
  [-9.0408914e-02  5.4436173e-02  4.6672925e-02]
  [-8.8086993e-02  5.4665931e-02  4.6051532e-02]]], shape=(1, 1420, 3), dtype=float32).
Traceback (most recent call last):

  File "/home/wrs/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 898, in generator_py_func
    flattened_values = nest.flatten_up_to(output_types, values)

  File "/home/wrs/.local/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 381, in flatten_up_to
    assert_shallow_structure(shallow_tree, input_tree)

  File "/home/wrs/.local/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 282, in assert_shallow_structure
    raise TypeError(

TypeError: If shallow structure is a sequence, input must also be a sequence. Input has type: <class 'tensorflow.python.framework.ops.EagerTensor'>.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/wrs/.local/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/home/wrs/.local/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 645, in wrapper
    return func(*args, **kwargs)

  File "/home/wrs/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 900, in generator_py_func
    six.reraise(

  File "/home/wrs/.local/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)

  File "/home/wrs/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 898, in generator_py_func
    flattened_values = nest.flatten_up_to(output_types, values)

  File "/home/wrs/.local/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 381, in flatten_up_to
    assert_shallow_structure(shallow_tree, input_tree)

  File "/home/wrs/.local/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 282, in assert_shallow_structure
    raise TypeError(

TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was (tf.float32, tf.int32, tf.float32), but the yielded element was tf.Tensor(
[[[ 1.0383280e-03 -1.5828928e-03  3.7101896e-03]
  [ 6.1125058e-05 -7.3752232e-04  2.3326376e-03]
  [ 9.6225485e-05 -5.3882645e-04  1.2442997e-03]
  ...
  [-9.0772845e-02  5.4567087e-02  4.6876539e-02]
  [-9.0408914e-02  5.4436173e-02  4.6672925e-02]
  [-8.8086993e-02  5.4665931e-02  4.6051532e-02]]], shape=(1, 1420, 3), dtype=float32).


	 [[{{node PyFunc}}]] [Op:IteratorGetNext]

## Utils Function

In [ ]:
def pprint(s, shape):
    print(s.center(35), ":",shape)

## PCN Development

In [ ]:
def get_file_paths(complete_dir, training=True):
    mid_pt = int(len(os.listdir(complete_dir))*7/9)
    start = 0 if training else mid_pt
    end = mid_pt if training else None
    return sorted(os.listdir(complete_dir))[start:end]

len(get_file_paths("data/complete/", training=0))

def xform(dir):
    return dir.replace("complete", "partial")

def get_pcds_np(complete_dir, training=True):
    partial, npts, complete = [], [], []
    cnt = 0
    for pcd_path in get_file_paths(complete_dir, training=True):
        complete.append(open3d_util.read_pcd(os.path.join(complete_dir, pcd_path)))
        partial.append(open3d_util.read_pcd(os.path.join(xform(complete_dir), xform(pcd_path))))
        npts.append(len(partial[-1]))
        cnt+=1
        if cnt%100 == 0: print("-",end=" ")
    return partial, npts, complete

partial, npts, complete = get_pcds_np("data/complete/", training=True)

import numpy as np
import os
checkpoint_name = "cp-{step}.ckpt"
checkpoint_name.format(step=10)
os.path.join("training",checkpoint_name.format(step=100))

a = [i for i in range(10)]
np.random.shuffle(a)
print(a)

In [ ]:
idx = np.random.permutation(24)
print(idx)
print(idx[:None])

def get_idx(idxs, bs):
    ids = []
    for i in range(int(np.ceil(len(idxs)/bs))):
        start = i*bs
        end = None if start+bs >= len(idxs) else start+bs
        print(start, end)
        ids.append(idxs.tolist()[start:end])
    return ids
print(get_idx(idx, 8))


In [ ]:
# ids, inputs, npts, gt
npts = [20, 30, 55]
partial = tf.random.normal((1,105,3))
complete = tf.random.normal((3,16384,3))

model = PCN()
coarse, fine = model((partial,npts), training=True)
pprint("Output Tensor (aft decoder): coarse-->", coarse.shape)
pprint("Output Tensor (aft decoder): fine-->", fine.shape)

In [ ]:
from loss_utils.emd import *

a = tf.random.normal((3,123,3))
b = tf.random.normal((3,123,3))

print( getEMD(a.numpy(),b.numpy()) )

In [ ]:
def mlp_conv(inputs, channels):
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Conv1D(channels[0], 1, activation='relu'))
    model.add(tf.keras.layers.Conv1D(channels[1], 1, activation='relu'))
    outputs = model(inputs)
    return outputs

def mlp(inputs, channels):
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Dense(channels[0], activation='relu'))
    model.add(tf.keras.layers.Dense(channels[1], activation='relu'))
    model.add(tf.keras.layers.Dense(channels[2], activation='relu'))
    outputs = model(inputs)
    return outputs

def point_maxpool(inputs, npts, keepdims=False):
    outputs = [tf.reduce_max(f, axis=1, keepdims=keepdims)
        for f in tf.split(inputs, npts, axis=1)]
    return tf.concat(outputs, axis=0)


def point_unpool(inputs, npts):
    inputs = tf.split(inputs, inputs.shape[0], axis=0)
    outputs = [tf.tile(f, [1, npts[i], 1]) for i,f in enumerate(inputs)]
    return tf.concat(outputs, axis=1)

# npts = [1024,1024,1024]
# x = tf.random.normal((3,1024,3))
# pprint("Input Tensor", x.shape)
# x = tf.reshape(x, [1, x.shape[1]*x.shape[0], 3])
npts = [20, 30, 55]
x = tf.random.normal((1,105,3))
pprint("Input Tensor (aft reshaping)", x.shape)
features = mlp_conv(x,[64,128])
pprint("Output Tensor (aft Conv1D)", features.shape)

features_1 = point_maxpool(features, npts, keepdims=1)
pprint("Output Tensor (aft maxpool)", features_1.shape)
features_global = point_unpool(features_1, npts)
pprint("Output Tensor (aft unpool)", features_global.shape)

features = tf.concat([features, features_global], axis=2)
pprint("Output Tensor (aft concat)", features.shape)

features = mlp_conv(features,[512,1024])
pprint("Output Tensor (aft 2nd conv)", features.shape)
features = point_maxpool(features,npts)
pprint("Output Tensor (aft 2nd maxpool)", features.shape)


coarse = mlp(features,[1024,1024, 1024*3])
pprint("Output Tensor (aft MLP)", coarse.shape)

coarse = tf.reshape(coarse, [-1, 1024, 3])
pprint("Output Tensor (aft reshaping)", coarse.shape)

"""
    Input Tensor (aft reshaping)    : (1, 105, 3)
     Output Tensor (aft Conv1D)     : (1, 105, 128)
    Output Tensor (aft maxpool)     : (3, 1, 128)
     Output Tensor (aft unpool)     : (1, 105, 128)
     Output Tensor (aft concat)     : (1, 105, 256)
    Output Tensor (aft 2nd conv)    : (1, 105, 1024)
  Output Tensor (aft 2nd maxpool)   : (3, 1024)
      Output Tensor (aft MLP)       : (3, 3072)
   Output Tensor (aft reshaping)    : (3, 1024, 3)
"""


## PCCN Development

Input Tensor (aft reshaping)      : (1, 105, 3)
Output Tensor (aft Conv1D)        : (1, 105, 128)
Output Tensor (aft maxpool)       : (3, 1, 128)
Output Tensor (aft unpool)        : (1, 105, 128)
Output Tensor (aft concat)        : (1, 105, 256)
Output Tensor (aft 2nd conv)      : (1, 105, 1024)
Output Tensor (aft 2nd maxpool)   : (3, 1024)

In [ ]:
partial = tf.random.normal((1,12,3))
x = tf.expand_dims(partial, axis=0)
print(x)

In [ ]:
x = tf.keras.layers.Conv2D(5, [1,3], activation='relu')(x)
print(x)

In [ ]:
import tensorflow as tf

npts = [20, 30, 55]
partial = tf.random.normal((1,105,3))
complete = tf.random.normal((3,16384,3))

x = tf.expand_dims(partial, axis=-1)
pprint("Input Tensor (aft expansion)", x.shape)
x = tf.keras.layers.Conv2D(64, [1,3], padding='valid', activation='relu')(x)
print(x.shape)
x = tf.keras.layers.Conv2D(128, 1,activation='relu')(x)
print(x.shape)
x = tf.keras.layers.Conv2D(256, 1, activation='relu')(x)
print(x.shape)
x = tf.keras.layers.MaxPool2D(pool_size=[105, 1], strides=(2, 2), padding='valid')(x)
print(x.shape)

In [ ]:
input_shape = (12, 189, 3, 1)
bs = input_shape[0]
num_pts = input_shape[1]

# Point functions (MLP implemented as conv2d)
# By default, Keras version of Conv2D has: strides=[1,1], padding="valid" , data_format="channels_last"
x = tf.random.normal(input_shape)
x = tf.keras.layers.Conv2D(64, [1,3], activation='relu')(x)
print(x.shape)
x = tf.keras.layers.Conv2D(64, [1,1],activation='relu')(x)
print(x.shape)
x = tf.keras.layers.Conv2D(64, [1,1], activation='relu')(x)
print(x.shape)
x = tf.keras.layers.Conv2D(128, [1,1], activation='relu')(x)
print(x.shape)
x = tf.keras.layers.Conv2D(1024, [1,1], activation='relu')(x)
print(x.shape)

# Symmetric function: max pooling
x = tf.keras.layers.MaxPool2D(pool_size=[num_pts, 1], strides=(2, 2), padding='valid')(x)
print(x.shape)

# MLP on global point cloud vector
x = tf.reshape(x, [bs, -1])
print(x.shape)
x = tf.keras.layers.Dense(1024,activation='relu')(x)
print(x.shape)
x = tf.keras.layers.Dense(512,activation='relu')(x)
print(x.shape)
x = tf.keras.layers.Dense(256,activation='relu')(x)
print(x.shape)

mean, logvar = tf.split(x, num_or_size_splits=2, axis=1)
print("Mean:",mean.shape, " Log(Var):",logvar.shape)